//
//  ErrorType.swift
//
//
//  Created by Faustino Flores García on 10/1/22.
//

public enum ErrorType: Int {
    case TRACK_CUSTOMER_ID_ERROR = -9
    case TRACK_EXTERNAL_EVENT_ERROR = -8
    case TRACK_SELPHID_ERROR = -7
    case TRACK_SELPHI_ERROR = -6
    case TRACK_START_ERROR = -5
    case TRACK_COORDINATES_ERROR = -4
    case TRACK_DEVICE_ERROR = -3
    case INIT_SESSION_ERROR = -2
    case INIT_PROCESS_ERROR = -1
    case NETWORK_CONNECTION = 0
    case TE_UNKNOWN_ERROR = 1
    case TE_NO_ERROR = 2
    case TE_CAMERA_PERMISSION_DENIED = 3
    case TE_SETTINGS_PERMISSION_ERROR = 4
    case TE_HARDWARE_ERROR = 5
    case TE_EXTRACTION_LICENSE_ERROR = 6
    case TE_UNEXPECTED_CAPTURE_ERROR = 7
    case TE_CONTROL_NOT_INITIALIZATED_ERROR = 8
    case TE_BAD_EXTRACTOR_CONFIGURATION_ERROR = 9
}
